name: Super Linter

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change directory to frontend/asl4all
        run: cd frontend/asl4all

      - name: Set up Super Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Super Linter
        run: |
          cd frontend/asl4all
          ./bin/run