name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend/asl4all
          npm install
          npm install tailwindcss
        
      - name: Build project
        run: |
          cd frontend/asl4all
          npm run build

      #- name: Run tests
        #run: npm test