name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run frontend test
        run: |
          cd frontend/asl4all
          npm i
          npm test

      - name: run backend test
        run: |
          cd backend
          npm i
          npm test
