name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run frontend test
        working-directory: frontend/asl4all
        run: |
          pwd
          npm i
          npm test

      - name: run backend test
        working-directory: backend
        run: |
          npm i
          npm test
