name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: run frontend test
        run: |
          cd frontend/asl4all
          npm i
          npm test

      - name: run backend test
        run: |
          cd backend
          npm i
          npm test
